- name: run kuber-deploy
  hosts: servers

  vars:
    cmd:
      - kind create cluster --config=./kubernetes/kind-config.yaml
      - kubectl apply -f kubernetes/namespace.yml
      - kubectl apply -f kubernetes/deployment.yml
      - kubectl apply -f kubernetes/service.yml
      - kubectl apply -f kubernetes/grafana-install.yml

  tasks:
    - name: run commands
      command: "{{ item }}"
      loop: "{{ cmd }}"
      register: result

    - name: show deployment output
      debug:
        msg: "{{ item.stdout }}"
      loop: "{{ result.results }}"