- name: create kubernetes directory
  file:
    path: /home/ubuntu/kubernetes
    state: directory
    mode: '0755'

- name: copy kubernetes files
  copy:
    src: "{{ project_dir }}/kubernetes/"
    dest: /home/ubuntu/kubernetes/

# - name: create kind cluster
#   command: kind create cluster --config=/home/ubuntu/kubernetes/kind-config.yaml

# - name: apply namespace
#   command: kubectl apply -f /home/ubuntu/kubernetes/namespace.yml

# - name: apply deployment
#   command: kubectl apply -f /home/ubuntu/kubernetes/deployment.yml

# - name: apply service
#   command: kubectl apply -f /home/ubuntu/kubernetes/service.yml

# - name: install grafana
#   command: kubectl apply -f /home/ubuntu/kubernetes/grafana-install.yml