[servers]

worker-node-1 ansible_host=192.168.33.130
; worker-node-2 ansible_host=<ip-address>

worker-node-1 ansible_user=ubuntu
; worker-node-2 ansible_user=<ubuntu>

[all:vars]
; ansible_ssh_private_key_file=<path>
ansible_python_interpreter=/usr/bin/python3
; ansible_host_key_checking=False


# ansible-playbook -i hosts.ini -a "apt-get update" --become -v


# --become  ........ sudo without commands.........
# -v    ............. see all logs in commands